# Generated by Django 6.0 on 2026-05-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('pdf', models.FileField(upload_to='papers/')),
            ],
        ),
    ]
