# Generated by Django 6.0.5 on 2026-06-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='board',
            field=models.CharField(default='ICSE', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='class_name',
            field=models.CharField(default='10', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(default='Physics', max_length=50),
        ),
    ]
