# Generated by Django 6.0.5 on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_question_board_question_class_name_question_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(
                blank=True,
                help_text='Cropped image of the question from the PDF (includes diagrams).',
                null=True,
                upload_to='question_crops/',
            ),
        ),
    ]
